spring:
  datasource:
    url: jdbc:tc:postgresql:15-alpine:///fluxpay
    username: test
    password: test
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
  jpa:
    show-sql: false

logging:
  level:
    com.payflow: INFO
