spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fluxpay
    username: fluxpay
    password: fluxpay
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  jwt:
    secret: dev-only-secret-key-that-is-long-enough-for-hmac-sha256-algorithm

logging:
  level:
    com.payflow: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
